name: github_gui_launcher
display_name: "GitHub GUI 启动器"
version: 1.0.0
description: "一键启动 GitHub Desktop 并打开指定仓库，支持本地路径和 GitHub URL"
author: trae.cn
category: 开发工具
tags:
  - "github"
  - "git"
  - "开发工具"
trigger:
  - "github"
  - "git"
  - "启动器"
  - "打开仓库"
inputs:
  - name: github_path
    type: string
    required: false
    default: ""
    description: GitHub仓库路径
  - name: client_type
    type: string
    required: false
    default: "default"
    description: GUI客户端类型
outputs:
  - name: status
    type: string
    description: 启动状态
  - name: message
    type: string
    description: 详细信息
requirements:
  - os
  - subprocess
  - json
